export const GET_ERRORS = "GET_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_RATING = "GET_RATING";
export const RATING_LOADING = "RATING_LOADING";
export const CLEAR_CURRENT_RATING = "CLEAR_CURRENT_RATING";

export const GET_CHANNELS = "GET_CHANNELS";
